# Generated by Django 4.2.7 on 2023-11-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                ("content", models.TextField(max_length=500)),
                ("time_stamp", models.DateField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
